### ISSUE TITLE
Workflow selection - Show available workflows

### ISSUE THREAD

**Issue by Aerendel** [AllenCell/napari-aicssegmentation#26]
**Story**
As a segmenter plugin user, I want to have access to available image channels and segmenter workflows so that I can start processing my data

**A/C**
I know this is done when...
- Given I am on the "Select workflow" screen
  And I have selected an image layer
  And I have selected an image channel
  Then I can see all available Segmenter workflows in a grid
  And interaction with the grid is enabled

- Given I am on the "Select workflow" screen
  And I have not selected an image layer
  Then I can see all available Segmenter workflows in a grid
  And the grid is disabled for interaction

- Given I am on the "Select workflow" screen
  And I have not selected an image channel
  Then I can see all available Segmenter workflows in a grid
  And the grid is disabled for interaction

  
**Details**
- Display available workflows as a selectable grid
- See https://docs.google.com/presentation/d/1zQ41ih3b3CzFrYqbT96phuEGq5Y8mrzo_MDHkLfE7Dg for wireframes
- Structure thumbnail images are provided by the Segmenter engine. This story should mainly be hooking up the UI to the segmenter engine. 
- Remember to handle state changes and enable / disable the grid in response to user deselecting layer / channel or those selections being reset for any other reason

**Comment by schoinh** [comment]
I asked Graham and @thao-do if it would be ok to disable individual buttons instead of disabling the entire section like the wireframe shows, at least for the FPP. I spent some time trying to figure out how to disable the whole section last Friday and it wasn't super straightforward. Graham said he would be happy with the disabling individual buttons workaround, but Graham and Thao are now discussing other alternatives for this too.

To move forward with this for now, I think we should just disable/enable all the individual buttons.
